name: release

on:
  push:
    tags:
    - "v*"

permissions:
  checks: write
  contents: write
  statuses: write

defaults:
  run:
    shell: bash

jobs:
  test:
    uses: ./.github/workflows/ci.yml
    with:
      version: ${{ github.ref_name }}

  publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
    # Check out with full history to generate release notes.
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download package
      uses: actions/download-artifact@v3
      with:
        name: artifact
        path: ${{ runner.temp }}/

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        cache: npm
        node-version: ${{ needs.test.outputs.node-version }}

    - name: Release
      run: gh release create ${{ github.ref_name }} --generate-notes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload package to release
      run: |
        gh release upload ${{ github.ref_name }} "${{ runner.temp }}/${{ needs.test.outputs.package-name }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish package
      run: |
        npm install -g @vscode/vsce
        vsce publish -p "$VSCE_TOKEN" --packagePath "${{ runner.temp }}/${{ needs.test.outputs.package-name }}"
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
